/** Generación end-to-end de la siguiente sesión canónica. */
function resolverCursoClassroomPorMateria_(materia){
 const courseId=obtenerCourseIdPorNombre(materia);
 const course=Classroom.Courses.get(String(courseId));
 if(String(course.courseState||'')!=='ACTIVE')throw new Error('El curso canónico no está ACTIVE: '+materia+'.');
 return course;
}
function leerPlaneacionSiguienteClase_(materia){const source=resolvePlanningSource_(materia),ss=SpreadsheetApp.openById(source.spreadsheetId);let sh=ss.getSheetByName(source.preferredSheet);if(!sh&&ss.getSheets().length===1)sh=ss.getSheets()[0];if(!sh)throw new Error('No existe hoja canónica.');const v=sh.getDataRange().getDisplayValues();const configuredHeader=Math.max(1,Number(source.headerRow||1));const hi=configuredHeader-1;if(!v[hi])throw new Error('No se encontró encabezado canónico.');const h=v[hi].map(normalizeGuard_),col=function(a){return findHeaderGuard_(h,a.filter(Boolean));},C={session:col([source.columns&&source.columns.session,'sesion','sesión','clase']),date:col(['fecha']),day:col(['dia','día']),time:col(['horario']),room:col(['aula']),unit:col([source.columns&&source.columns.unit,'unidad']),topic:col([source.columns&&source.columns.topic,'subtema curricular (desglose de planeación)','tema / subtema','tema/subtema','tema / alcance','tema/alcance','tema']),tools:col(['software / herramientas']),practiceDescription:col(['descripcion de la practica (min. 60 min)','descripción de la práctica (mín. 60 min)','aplicación en clase']),evidence:col(['evidencia verificable','evidencia de clase']),practice:col(['recurso de aplicacion','recurso de aplicación','practica del dia','práctica del día','actividad / práctica vinculada','actividad / practica vinculada']),topicFallback:col(['nombre del subtema','tema / subtema','subtema']),previous:col(['tarea previa a esta clase','material previo']),next:col(['tarea siguiente / preparacion para la proxima clase','tarea siguiente / preparación para la próxima clase','tarea siguiente / preparación siguiente']),gamma:col(['presentacion gamma','presentación gamma','complemento docente / gamma']),gammaUrl:col(['enlace gamma','enlace / id gamma']),gammaState:col(['estado de enlace','estado integral de la sesión']),classroomIds:col(['id / estado classroom']),prompt:col(['prompt gamma de la clase (incluye link a la practica)','prompt gamma de la clase (incluye link a la práctica)'])};const rows=v.slice(hi+1).map(function(r,i){const o={row:hi+i+2};Object.keys(C).forEach(function(k){o[k]=C[k]>=0?r[C[k]]:'';});if(!String(o.topic||'').trim())o.topic=String(o.topicFallback||'').trim();return o;}).filter(function(x){return String(x.topic||'').trim();});return{source:source,sheet:sh,rows:rows};}
function tituloTareaPreviaClase_(row){return 'Tarea previa - '+String(row.topic||'').trim();}function tituloPracticaClase_(row){return String(row.practice||'').trim();}
function listarCourseWorkClase_(courseId){let token,out=[];do{const p=Classroom.Courses.CourseWork.list(String(courseId),{pageSize:100,pageToken:token,courseWorkStates:['DRAFT','PUBLISHED']});out=out.concat(p.courseWork||[]);token=p.nextPageToken;}while(token);return out.filter(function(w){return String(w.state||'').toUpperCase()!=='DELETED';});}function buscarWorkTitulo_(works,title){return works.find(function(w){return String(w.title||'').trim()===String(title||'').trim();})||null;}function claveProgresoClase_(courseId){return 'NEXT_CLASS_LAST_COMPLETED_'+String(courseId);}
function resolverSiguienteClase(materia,requestedSession,options){
 const subject=String(materia||'').trim();if(!subject)throw new Error('materia es obligatoria.');
 const plan=leerPlaneacionSiguienteClase_(subject);
 const course=resolverCursoClassroomPorMateria_(subject);
 const works=listarCourseWorkClase_(course.id);
 const state=seleccionarSiguienteClasePorEstadoReal_(plan.rows,works,requestedSession,options);
 if(state.complete)return {ok:true,complete:true,materia:subject,courseId:String(course.id),courseName:course.name,sequenceSource:state.source,observed:state.observed};
 const target=state.target,evidence=state.evidence;
 const targetIndex=plan.rows.findIndex(function(r){return Number(r.row)===Number(target.row);});
 const nextTarget=targetIndex>=0&&targetIndex+1<plan.rows.length?plan.rows[targetIndex+1]:null;
 const prev=buscarWorkTitulo_(works,tituloTareaPreviaClase_(target));
 const practice=buscarWorkTitulo_(works,tituloPracticaClase_(target));
 return {ok:true,complete:false,materia:subject,courseId:String(course.id),courseName:course.name,
  planningSpreadsheetId:plan.source.spreadsheetId,planningSheet:plan.sheet.getName(),target:target,nextTarget:nextTarget,
  evidence:evidence,sequenceSource:state.source,inferredSession:state.inferredSession,
  reconciliation:state.reconciliation,progress:{lastPrepared:state.lastPrepared,lastPublished:state.lastPublished},
  missing:{tareaPrevia:!prev,gamma:!evidence.gammaVerificada,practica:!practice},resourceState:'DRAFT'};
}
function crearTareaPaquete_(courseId,materia,row,title,description,dueDate,dueTime){const existing=buscarWorkTitulo_(listarCourseWorkClase_(courseId),title);if(existing)return{workId:String(existing.id),estado:existing.state,reutilizado:true,classroomUrl:existing.alternateLink||''};const req={operation:'RESOURCE_CREATE',materia:materia,temaSubtema:row.topic,resourceType:'TAREA',resourceState:'DRAFT'};preflightDocumentoMaestro(req);const body={title:title,description:description,workType:'ASSIGNMENT',state:'DRAFT',maxPoints:100},topicId=resolveTopicId_(courseId,'',row.unit);if(topicId)body.topicId=topicId;if(dueDate){const m=dueDate.match(/^(\d{4})-(\d{2})-(\d{2})$/),t=String(dueTime||'11:00').match(/^(\d{1,2}):(\d{2})$/);if(m&&t){body.dueDate={year:+m[1],month:+m[2],day:+m[3]};body.dueTime={hours:+t[1],minutes:+t[2]};}}const w=Classroom.Courses.CourseWork.create(body,String(courseId)),verified=verificarCourseWorkDraftDirecto_(courseId,w.id);postflightDocumentoMaestro({ok:true,state:verified.state,workId:verified.id},req);return{workId:String(verified.id),estado:verified.state,reutilizado:false,classroomUrl:verified.alternateLink||''};}
function contenidoPracticaDesdePlaneacion_(row){return ['Objetivo y aplicación',String(row.practiceDescription||row.practice||''),'','Herramientas',String(row.tools||''),'','Procedimiento','1. Revisa el objetivo, las herramientas y la evidencia esperada antes de comenzar.','2. Ejecuta la actividad de forma incremental y conserva evidencia verificable de cada etapa.','3. Relaciona cada resultado con '+String(row.topic||'el tema de la sesión')+'.','4. Documenta errores, ajustes y resultado final sin incluir credenciales ni datos sensibles.','','Evidencia verificable',String(row.evidence||''),'','Preparación previa relacionada',String(row.previous||''),'','Cierre','Explica brevemente qué observaste, qué evidencia respalda tu conclusión y qué cambiarías en una segunda ejecución.'].join('\n');}
function fechaIsoPlaneacion_(s){const m=String(s||'').match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?m[3]+'-'+m[2]+'-'+m[1]:'';}function horaInicio_(s){const m=String(s||'').match(/(\d{1,2}:\d{2})/);return m?m[1]:'11:00';}
/** Conservado sólo como referencia; el entrypoint vigente está en 44_NomenclaturaRecursos.gs. */
function generarSiguienteClaseLegacy_(params){throw new Error('ENTRYPOINT_LEGACY_DESHABILITADO');}
