/** Nomenclatura canónica: tipo NN - tema/subtema. La numeración parte del último recurso PUBLICADO, nunca de la sesión. */
function numero2_(n){return ('0'+Number(n)).slice(-2);}
function maxPublicadoPorTipo_(works,tipo){const re=tipo==='TAREA'?/^Tarea\s+(\d+)\b/i:/^Práctica\s+(\d+)\b/i;let max=0;(works||[]).forEach(function(w){if(String(w.state||'').toUpperCase()!=='PUBLISHED')return;const m=String(w.title||'').trim().match(re);if(m)max=Math.max(max,Number(m[1])||0);});return max;}
function tituloTareaNumerada_(n,row){return 'Tarea '+numero2_(n)+' - '+String(row.topic||'').trim();}
function tituloPracticaNumerada_(n,row){const base='Práctica '+numero2_(n)+' - '+String(row.topic||'').trim(),desc=String(row.practiceDescription||'').trim();return desc?base+' - '+desc:base;}
function borrarDraftPorId_(courseId,id){try{const w=Classroom.Courses.CourseWork.get(String(courseId),String(id));if(String(w.state||'').toUpperCase()==='DRAFT'){Classroom.Courses.CourseWork.remove(String(courseId),String(id));return true;}}catch(e){}return false;}
function generarSiguienteClase(params){const p=params&&typeof params==='object'?params:{},materia=String(p.materia||'Sistemas Distribuidos').trim(),plan=leerPlaneacionSiguienteClase_(materia),course=resolverCursoClassroomPorMateria_(materia),courseId=String(course.id),works0=listarCourseWorkClase_(courseId);let row=null;if(p.sesion){row=plan.rows.find(function(r){return String(r.session)===String(p.sesion);});}else{const last=Number(PropertiesService.getScriptProperties().getProperty(claveProgresoClase_(courseId))||0);row=plan.rows.find(function(r){return Number(r.session)>last&&!/evaluacion/i.test(String(r.topic||''));})||null;}if(!row)throw new Error('No se pudo resolver la siguiente sesión canónica.');const idx=plan.rows.findIndex(function(x){return x.row===row.row;}),nextRow=idx>=0&&idx+1<plan.rows.length?plan.rows[idx+1]:null;
const taskBase=maxPublicadoPorTipo_(works0,'TAREA'),practiceBase=maxPublicadoPorTipo_(works0,'PRACTICA'),currentTaskNo=taskBase+1,nextTaskNo=taskBase+2,currentPracticeNo=practiceBase+1,prevTitle=tituloTareaNumerada_(currentTaskNo,row),practiceTitle=tituloPracticaNumerada_(currentPracticeNo,row),results={};
results.tareaPrevia=crearTareaPaquete_(courseId,materia,row,prevTitle,row.previous,'','');if(!/^https:\/\/gamma\.app\//i.test(String(row.gammaUrl||'')))throw new Error('PAQUETE_INCOMPLETO: falta Gamma canónica para '+row.topic+'.');results.gamma={url:row.gammaUrl,verified:true};results.practica=crearPractica({courseId:courseId,materia:materia,temaSubtema:row.topic,courseKey:'UAQ_SISTEMAS_DISTRIBUIDOS',unidad:row.unit,topicName:row.unit,titulo:practiceTitle,descripcion:'Práctica formal: '+row.topic+'.',contenidoDocumento:contenidoPracticaDesdePlaneacion_(row),studentCopy:true});if(nextRow&&String(row.next||'').trim())results.tareaSiguiente=crearTareaPaquete_(courseId,materia,row,tituloTareaNumerada_(nextTaskNo,nextRow),row.next,fechaIsoPlaneacion_(nextRow.date),horaInicio_(nextRow.time));
const works=listarCourseWorkClase_(courseId),checks={tareaActual:!!buscarWorkTitulo_(works,prevTitle),practica:!!buscarWorkTitulo_(works,practiceTitle),gamma:true,tareaSiguiente:!nextRow||!String(row.next||'').trim()||!!buscarWorkTitulo_(works,tituloTareaNumerada_(nextTaskNo,nextRow))};if(Object.keys(checks).some(function(k){return !checks[k];}))throw new Error('POSTFLIGHT_PAQUETE_INCOMPLETO: '+JSON.stringify(checks));PropertiesService.getScriptProperties().setProperty(claveProgresoClase_(courseId),String(row.session));return{ok:true,verified:true,materia:materia,courseId:courseId,target:row,numbering:{lastPublishedTask:taskBase,lastPublishedPractice:practiceBase,currentTask:currentTaskNo,currentPractice:currentPracticeNo,nextTask:nextTaskNo},titles:{tareaActual:prevTitle,practica:practiceTitle,tareaSiguiente:nextRow?tituloTareaNumerada_(nextTaskNo,nextRow):''},results:results,checks:checks,resourceState:'DRAFT'};}
function generarSiguienteClaseSistemasDistribuidos(){return generarSiguienteClase({materia:'Sistemas Distribuidos'});}
function limpiarDraftsNoCanonicosSesion15SistemasDistribuidos(){const courseId='871158466533',keep=[/^Tarea 07 - 2\.2\.4 Mensajes de requerimiento HTTP$/i,/^Práctica 07 - 2\.2\.4 Mensajes de requerimiento HTTP\b/i,/^Tarea 08 - 2\.2\.5 Mensajes de respuesta HTTP$/i],deleted=[];listarCourseWorkClase_(courseId).forEach(function(w){if(String(w.state||'').toUpperCase()!=='DRAFT')return;const t=String(w.title||'').trim(),related=/2\.2\.4 Mensajes de requerimiento HTTP|2\.2\.5 Mensajes de respuesta HTTP|^Práctica 14\b|^Tarea previa\b/i.test(t);if(related&&!keep.some(function(re){return re.test(t);})&&borrarDraftPorId_(courseId,w.id))deleted.push({id:String(w.id),title:t});});return deleted;}
/** Corrige DRAFT erróneos de la sesión 15, conserva sólo nomenclatura canónica y verifica el paquete final. */
function repararDraftsSesion15SistemasDistribuidos(){const courseId='871158466533',deleted=limpiarDraftsNoCanonicosSesion15SistemasDistribuidos();PropertiesService.getScriptProperties().setProperty(claveProgresoClase_(courseId),'14');const result=generarSiguienteClase({materia:'Sistemas Distribuidos',sesion:15}),remaining=listarCourseWorkClase_(courseId).filter(function(w){return String(w.state||'').toUpperCase()==='DRAFT'&&/2\.2\.4 Mensajes de requerimiento HTTP|2\.2\.5 Mensajes de respuesta HTTP/i.test(String(w.title||''));}).map(function(w){return{id:String(w.id),title:w.title,state:w.state};});const expected=[result.titles.tareaActual,result.titles.practica,result.titles.tareaSiguiente],unexpected=remaining.filter(function(w){return expected.indexOf(w.title)<0;});if(unexpected.length)throw new Error('POSTFLIGHT_DRAFTS_NO_CANONICOS: '+JSON.stringify(unexpected));return{ok:true,verified:true,deletedWrongDrafts:deleted,remainingCanonicalDrafts:remaining,result:result};}
