/** Nomenclatura canónica: tipo NN - tema/subtema. La numeración parte del último recurso PUBLICADO, nunca de la sesión. */
function numero2_(n){return ('0'+Number(n)).slice(-2);}
function maxPublicadoPorTipo_(works,tipo){const re=tipo==='TAREA'?/^Tarea\s+(\d+)\b/i:/^Práctica\s+(\d+)\b/i;let max=0;(works||[]).forEach(function(w){if(String(w.state||'').toUpperCase()!=='PUBLISHED')return;const m=String(w.title||'').trim().match(re);if(m)max=Math.max(max,Number(m[1])||0);});return max;}
function tituloTareaNumerada_(n,row){return 'Tarea '+numero2_(n)+' - '+String(row.topic||'').trim();}
function tituloPracticaNumerada_(n,row){const base='Práctica '+numero2_(n)+' - '+String(row.topic||'').trim(),desc=String(row.practiceDescription||'').trim();return desc?base+' - '+desc:base;}
function borrarDraftPorId_(courseId,id){try{const w=Classroom.Courses.CourseWork.get(String(courseId),String(id));if(String(w.state||'').toUpperCase()==='DRAFT'){Classroom.Courses.CourseWork.remove(String(courseId),String(id));return true;}}catch(e){}return false;}
function generarSiguienteClase(params){
 const p=params&&typeof params==='object'?params:{};
 const materia=String(p.materia||'Sistemas Distribuidos').trim();
 // El generador histórico fabrica una PRÁCTICA de Sistemas Distribuidos:
 // se bloquea su uso para otras materias antes de tocar Classroom.
 if(!/^(?:UAQ - )?Sistemas Distribuidos$/i.test(materia))
   throw new Error('BLOCKED_UNSUPPORTED_CLASS_GENERATOR: usar el paquete específico de la materia; no crear una práctica de Sistemas Distribuidos en otro curso.');
 const resolved=resolverSiguienteClase(materia,p.sesion,{
   reconciliationMode:p.reconciliationMode===true,
   reconciliationReason:p.reconciliationReason
 });
 if(resolved.complete)return resolved;
 const row=resolved.target,courseId=resolved.courseId;
 const plan=leerPlaneacionSiguienteClase_(materia),works0=listarCourseWorkClase_(courseId);
 const idx=plan.rows.findIndex(function(x){return x.row===row.row;});
 const nextRow=idx>=0&&idx+1<plan.rows.length?plan.rows[idx+1]:null;
 // Validar secuencia y Gamma ANTES de crear la primera tarea.
 if(resolved.sequenceSource!=='CLASSROOM_GAMMA_REAL_STATE'||!resolved.evidence.gammaVerificada)
   throw new Error('BLOCKED_CLASS_PACKAGE_GAMMA: falta Gamma verificada para la sesión objetivo; auditar/reutilizar antes de mutar Classroom.');
 if(!String(row.practice||'').trim())
   throw new Error('BLOCKED_CLASS_PACKAGE_PRACTICE: la planeación no define práctica/actividad verificable.');
 const taskBase=maxPublicadoPorTipo_(works0,'TAREA'),practiceBase=maxPublicadoPorTipo_(works0,'PRACTICA'),currentTaskNo=taskBase+1,nextTaskNo=taskBase+2,currentPracticeNo=practiceBase+1,prevTitle=tituloTareaNumerada_(currentTaskNo,row),practiceTitle=tituloPracticaNumerada_(currentPracticeNo,row),results={};
results.tareaPrevia=crearTareaPaquete_(courseId,materia,row,prevTitle,row.previous,'','');results.gamma={url:row.gammaUrl,verified:true};results.practica=crearPractica({courseId:courseId,materia:materia,temaSubtema:row.topic,courseKey:'UAQ_SISTEMAS_DISTRIBUIDOS',unidad:row.unit,topicName:row.unit,titulo:practiceTitle,descripcion:'Práctica formal: '+row.topic+'.',contenidoDocumento:contenidoPracticaDesdePlaneacion_(row),studentCopy:true});if(nextRow&&String(row.next||'').trim())results.tareaSiguiente=crearTareaPaquete_(courseId,materia,row,tituloTareaNumerada_(nextTaskNo,nextRow),row.next,fechaIsoPlaneacion_(nextRow.date),horaInicio_(nextRow.time));
const works=listarCourseWorkClase_(courseId),checks={tareaActual:!!buscarWorkTitulo_(works,prevTitle),practica:!!buscarWorkTitulo_(works,practiceTitle),gamma:true,tareaSiguiente:!nextRow||!String(row.next||'').trim()||!!buscarWorkTitulo_(works,tituloTareaNumerada_(nextTaskNo,nextRow))};if(Object.keys(checks).some(function(k){return !checks[k];}))throw new Error('POSTFLIGHT_PAQUETE_INCOMPLETO: '+JSON.stringify(checks));return{ok:true,verified:true,materia:materia,courseId:courseId,target:row,numbering:{lastPublishedTask:taskBase,lastPublishedPractice:practiceBase,currentTask:currentTaskNo,currentPractice:currentPracticeNo,nextTask:nextTaskNo},titles:{tareaActual:prevTitle,practica:practiceTitle,tareaSiguiente:nextRow?tituloTareaNumerada_(nextTaskNo,nextRow):''},results:results,checks:checks,resourceState:'DRAFT',sequenceSource:resolved.sequenceSource,evidence:resolved.evidence};}
function generarSiguienteClaseSistemasDistribuidos(){return generarSiguienteClase({materia:'Sistemas Distribuidos'});}
function limpiarDraftsNoCanonicosSesion15SistemasDistribuidos(){const courseId='871158466533',keep=[/^Tarea 07 - 2\.2\.4 Mensajes de requerimiento HTTP$/i,/^Práctica 07 - 2\.2\.4 Mensajes de requerimiento HTTP\b/i,/^Tarea 08 - 2\.2\.5 Mensajes de respuesta HTTP$/i],deleted=[];listarCourseWorkClase_(courseId).forEach(function(w){if(String(w.state||'').toUpperCase()!=='DRAFT')return;const t=String(w.title||'').trim(),related=/2\.2\.4 Mensajes de requerimiento HTTP|2\.2\.5 Mensajes de respuesta HTTP|^Práctica 14\b|^Tarea previa\b/i.test(t);if(related&&!keep.some(function(re){return re.test(t);})&&borrarDraftPorId_(courseId,w.id))deleted.push({id:String(w.id),title:t});});return deleted;}
function deduplicarDraftsTitulos_(courseId,titles){const deleted=[];(titles||[]).forEach(function(title){const matches=listarCourseWorkClase_(courseId).filter(function(w){return String(w.state||'').toUpperCase()==='DRAFT'&&String(w.title||'').trim()===title;}).sort(function(a,b){return String(a.creationTime||'').localeCompare(String(b.creationTime||''));});matches.slice(1).forEach(function(w){if(borrarDraftPorId_(courseId,w.id))deleted.push({id:String(w.id),title:w.title,reason:'DUPLICATE'});});});return deleted;}
/** Corrige DRAFT erróneos de la sesión 15, conserva exactamente un recurso por título canónico y verifica el paquete final. */
function repararDraftsSesion15SistemasDistribuidos(){const courseId='871158466533',deleted=limpiarDraftsNoCanonicosSesion15SistemasDistribuidos();const result=generarSiguienteClase({materia:'Sistemas Distribuidos',sesion:15}),expected=[result.titles.tareaActual,result.titles.practica,result.titles.tareaSiguiente];Array.prototype.push.apply(deleted,deduplicarDraftsTitulos_(courseId,expected));const remaining=listarCourseWorkClase_(courseId).filter(function(w){return String(w.state||'').toUpperCase()==='DRAFT'&&/2\.2\.4 Mensajes de requerimiento HTTP|2\.2\.5 Mensajes de respuesta HTTP/i.test(String(w.title||''));}).map(function(w){return{id:String(w.id),title:w.title,state:w.state};}),unexpected=remaining.filter(function(w){return expected.indexOf(w.title)<0;}),counts={};remaining.forEach(function(w){counts[w.title]=(counts[w.title]||0)+1;});const duplicates=Object.keys(counts).filter(function(t){return counts[t]!==1;});if(unexpected.length||duplicates.length||remaining.length!==expected.length)throw new Error('POSTFLIGHT_DRAFTS_NO_CANONICOS: '+JSON.stringify({unexpected:unexpected,duplicates:duplicates,remaining:remaining}));return{ok:true,verified:true,deletedWrongDrafts:deleted,remainingCanonicalDrafts:remaining,result:result};}
/** Normaliza títulos de Tareas y Prácticas ya PUBLICADAS sin alterar estado, fechas, puntos ni entregas. */
function corregirNomenclaturaPublicadaSistemasDistribuidos(){const courseId='871158466533',works=listarCourseWorkClase_(courseId),cambios=[];works.filter(function(w){return String(w.state||'').toUpperCase()==='PUBLISHED';}).forEach(function(w){const old=String(w.title||'').trim();let nuevo=old,m=old.match(/^Tarea\s+(\d+)\s*-\s*(.+)$/i);if(m)nuevo='Tarea '+numero2_(m[1])+' - '+m[2].trim();else{m=old.match(/^Práctica\s+(\d+)\s*-\s*(.+)$/i);if(m)nuevo='Práctica '+numero2_(m[1])+' - '+m[2].trim();}if(nuevo!==old){Classroom.Courses.CourseWork.patch({title:nuevo},courseId,String(w.id),{updateMask:'title'});cambios.push({id:String(w.id),antes:old,despues:nuevo});}});const final=listarCourseWorkClase_(courseId),mal=final.filter(function(w){if(String(w.state||'').toUpperCase()!=='PUBLISHED')return false;const t=String(w.title||'').trim();return /^(Tarea|Práctica)\s+\d\s*-/.test(t);}).map(function(w){return{id:String(w.id),title:w.title};});if(mal.length)throw new Error('POSTFLIGHT_NOMENCLATURA_PUBLICADA: '+JSON.stringify(mal));return{ok:true,verified:true,courseId:courseId,updated:cambios,remainingNonCanonical:mal};}
