/** Reparación idempotente: prácticas formales de sesiones 11 a 13, sin alterar trabajos publicados. */
function completarPracticasSistemasOperativosITQ() {
 const course=resolverCursoClassroomPorMateria_('Sistemas Operativos'), courseId=String(course.id);
 if(courseId!=='875776451793')throw new Error('Identidad del curso distinta de la auditada.');
 const specs=[
 {n:11,topic:'Control e información de procesos',title:'Práctica 04 - Control e información de procesos',description:'Investigar la información de un proceso real en Windows 10/11 y distinguir datos observables de información interna del PCB.',content:['Objetivo: relacionar PID, PPID, nombre, ruta, CPU y memoria con la administración de procesos.','1. Abre PowerShell en Windows 10/11 sin privilegios de administrador. Ejecuta Get-Process | Select-Object -First 8 Name,Id,CPU,WorkingSet64. Registra tres procesos y explica qué significa cada columna.','2. Elige un proceso propio y ejecuta Get-CimInstance Win32_Process -Filter "ProcessId = PID" | Select-Object ProcessId,ParentProcessId,Name,ExecutablePath,CreationDate (sustituye PID por el número elegido). Si una propiedad no está disponible, registra la limitación.','3. Contrasta PID, uso de memoria y nombre con Administrador de tareas; no finalices procesos ajenos ni del sistema.','4. Distingue qué datos observaste realmente y cuáles pertenecen al contexto interno del proceso y no están expuestos por esas herramientas.','Evidencia: tabla de tres procesos, ficha de un proceso con PID/PPID/CPU/memoria y capturas sin información personal.','Cierre: explica por qué el PID no es una identidad permanente y qué podría impedir consultar un proceso.']},
 {n:12,topic:'Creación y terminación de procesos',title:'Práctica 05 - Creación y terminación de procesos',description:'Crear, observar y terminar de forma controlada un proceso propio en Windows 10/11 con PowerShell.',content:['Objetivo: identificar creación, ejecución, espera y terminación de un proceso hijo sin intervenir procesos del sistema.','1. Abre PowerShell en Windows 10/11. Ejecuta $p = Start-Process notepad.exe -PassThru; registra $p.Id y la hora de inicio.','2. Ejecuta Get-Process -Id $p.Id | Select-Object Id,ProcessName,StartTime,Responding y documenta el resultado.','3. Cierra manualmente la ventana del Bloc de notas; ejecuta Wait-Process -Id $p.Id -ErrorAction SilentlyContinue y comprueba con Get-Process -Id $p.Id -ErrorAction SilentlyContinue que ya no aparece.','4. Explica la diferencia entre esperar la terminación, consultar el estado y forzar la finalización. No uses Stop-Process sobre procesos ajenos.','Evidencia: comandos y salidas comentadas con PID, secuencia temporal, captura de ejecución y comprobación de terminación.','Cierre: razona qué sucede si el PID ya no existe al ejecutar Wait-Process.']},
 {n:13,topic:'Procesos e hilos',title:'Práctica 06 - Procesos e hilos',description:'Observar procesos e hilos en Windows 10/11 y ejecutar un ejemplo multihilo seguro.',content:['Objetivo: comparar identidad de proceso y concurrencia de hilos en una aplicación propia.','1. En PowerShell de Windows 10/11 ejecuta $p=Get-Process -Id $PID; $p | Select-Object Id,ProcessName,@{N="Hilos";E={$_.Threads.Count}},CPU,WorkingSet64 y registra los valores.','2. Ejecuta $jobs=1..3 | ForEach-Object { Start-ThreadJob -ScriptBlock { Start-Sleep -Seconds 5; [System.Threading.Thread]::CurrentThread.ManagedThreadId } }; $jobs | Wait-Job | Receive-Job; $jobs | Remove-Job. Si Start-ThreadJob no está disponible, registra la versión de PowerShell y documenta la limitación sin instalar software.','3. Consulta nuevamente el número de hilos del proceso propio y explica por qué una observación puntual puede no capturar todos los hilos temporales.','4. Compara proceso e hilo: memoria compartida, identificador, aislamiento y costos de coordinación; distingue concurrencia de paralelismo.','Evidencia: código ejecutado, salida y tabla de observaciones antes/durante/después, más explicación de dos limitaciones de la medición.','Cierre: justifica cuándo varios hilos ayudan y cuándo introducen riesgos de sincronización.']}
 ];
 const out=[];for(const s of specs){const existing=listarCourseWorkClase_(courseId).filter(w=>String(w.title||'').trim()===s.title);if(existing.length){out.push({session:s.n,reused:true,id:String(existing[0].id),state:existing[0].state});continue;}const r=crearPractica({courseId:courseId,courseKey:'ITQ_SO',materia:'Sistemas Operativos',temaSubtema:s.topic,unidad:'2',titulo:s.title,descripcion:s.description,contenidoDocumento:s.content.join('\n')});out.push({session:s.n,id:r.workId,state:r.estado,documentId:r.documentId});}return{ok:true,courseId:courseId,results:out};
}